# coding: utf-8

"""
    Easyc External

    API para processo externo  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tecnologia@easycredito.me
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Bank(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bank': 'Banks',
        'account_type': 'AccountType',
        'agency': 'str',
        'account': 'str'
    }

    attribute_map = {
        'bank': 'bank',
        'account_type': 'accountType',
        'agency': 'agency',
        'account': 'account'
    }

    def __init__(self, bank=None, account_type=None, agency=None, account=None):  # noqa: E501
        """Bank - a model defined in Swagger"""  # noqa: E501
        self._bank = None
        self._account_type = None
        self._agency = None
        self._account = None
        self.discriminator = None
        self.bank = bank
        self.account_type = account_type
        self.agency = agency
        self.account = account

    @property
    def bank(self):
        """Gets the bank of this Bank.  # noqa: E501


        :return: The bank of this Bank.  # noqa: E501
        :rtype: Banks
        """
        return self._bank

    @bank.setter
    def bank(self, bank):
        """Sets the bank of this Bank.


        :param bank: The bank of this Bank.  # noqa: E501
        :type: Banks
        """
        if bank is None:
            raise ValueError("Invalid value for `bank`, must not be `None`")  # noqa: E501

        self._bank = bank

    @property
    def account_type(self):
        """Gets the account_type of this Bank.  # noqa: E501


        :return: The account_type of this Bank.  # noqa: E501
        :rtype: AccountType
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type):
        """Sets the account_type of this Bank.


        :param account_type: The account_type of this Bank.  # noqa: E501
        :type: AccountType
        """
        if account_type is None:
            raise ValueError("Invalid value for `account_type`, must not be `None`")  # noqa: E501

        self._account_type = account_type

    @property
    def agency(self):
        """Gets the agency of this Bank.  # noqa: E501

        Número da agência  # noqa: E501

        :return: The agency of this Bank.  # noqa: E501
        :rtype: str
        """
        return self._agency

    @agency.setter
    def agency(self, agency):
        """Sets the agency of this Bank.

        Número da agência  # noqa: E501

        :param agency: The agency of this Bank.  # noqa: E501
        :type: str
        """
        if agency is None:
            raise ValueError("Invalid value for `agency`, must not be `None`")  # noqa: E501

        self._agency = agency

    @property
    def account(self):
        """Gets the account of this Bank.  # noqa: E501

        Número da conta  # noqa: E501

        :return: The account of this Bank.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this Bank.

        Número da conta  # noqa: E501

        :param account: The account of this Bank.  # noqa: E501
        :type: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Bank, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Bank):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
