# coding: utf-8

"""
    Easyc External

    API para processo externo  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tecnologia@easycredito.me
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Document(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'DocumentType',
        'mime_type': 'MimeType',
        'name': 'str',
        'url': 'str',
        'date_created': 'str'
    }

    attribute_map = {
        'type': 'type',
        'mime_type': 'mimeType',
        'name': 'name',
        'url': 'url',
        'date_created': 'dateCreated'
    }

    def __init__(self, type=None, mime_type=None, name=None, url=None, date_created=None):  # noqa: E501
        """Document - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._mime_type = None
        self._name = None
        self._url = None
        self._date_created = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if mime_type is not None:
            self.mime_type = mime_type
        if name is not None:
            self.name = name
        if url is not None:
            self.url = url
        if date_created is not None:
            self.date_created = date_created

    @property
    def type(self):
        """Gets the type of this Document.  # noqa: E501


        :return: The type of this Document.  # noqa: E501
        :rtype: DocumentType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Document.


        :param type: The type of this Document.  # noqa: E501
        :type: DocumentType
        """

        self._type = type

    @property
    def mime_type(self):
        """Gets the mime_type of this Document.  # noqa: E501


        :return: The mime_type of this Document.  # noqa: E501
        :rtype: MimeType
        """
        return self._mime_type

    @mime_type.setter
    def mime_type(self, mime_type):
        """Sets the mime_type of this Document.


        :param mime_type: The mime_type of this Document.  # noqa: E501
        :type: MimeType
        """

        self._mime_type = mime_type

    @property
    def name(self):
        """Gets the name of this Document.  # noqa: E501

        Nome do documento  # noqa: E501

        :return: The name of this Document.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Document.

        Nome do documento  # noqa: E501

        :param name: The name of this Document.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this Document.  # noqa: E501

        Url do documento  # noqa: E501

        :return: The url of this Document.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Document.

        Url do documento  # noqa: E501

        :param url: The url of this Document.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def date_created(self):
        """Gets the date_created of this Document.  # noqa: E501

        Data de Criação do Documento  # noqa: E501

        :return: The date_created of this Document.  # noqa: E501
        :rtype: str
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this Document.

        Data de Criação do Documento  # noqa: E501

        :param date_created: The date_created of this Document.  # noqa: E501
        :type: str
        """

        self._date_created = date_created

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Document, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Document):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
