# coding: utf-8

"""
    Easyc External

    API para processo externo  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tecnologia@easycredito.me
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from easycredito.models.error import Error


class ErrorFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'ErrorCode',
        'message': 'str',
        'errors': 'list[ErrorField]'
    }
    if hasattr(Error, "swagger_types"):
        swagger_types.update(Error.swagger_types)

    attribute_map = {
        'code': 'code',
        'message': 'message',
        'errors': 'errors'
    }
    if hasattr(Error, "attribute_map"):
        attribute_map.update(Error.attribute_map)

    def __init__(self, code=None, message=None, errors=None, *args, **kwargs):  # noqa: E501
        """ErrorFields - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._message = None
        self._errors = None
        self.discriminator = None
        self.code = code
        self.message = message
        if errors is not None:
            self.errors = errors
        Error.__init__(self, *args, **kwargs)

    @property
    def code(self):
        """Gets the code of this ErrorFields.  # noqa: E501


        :return: The code of this ErrorFields.  # noqa: E501
        :rtype: ErrorCode
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorFields.


        :param code: The code of this ErrorFields.  # noqa: E501
        :type: ErrorCode
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this ErrorFields.  # noqa: E501

        Mensagem de erro  # noqa: E501

        :return: The message of this ErrorFields.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorFields.

        Mensagem de erro  # noqa: E501

        :param message: The message of this ErrorFields.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def errors(self):
        """Gets the errors of this ErrorFields.  # noqa: E501


        :return: The errors of this ErrorFields.  # noqa: E501
        :rtype: list[ErrorField]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this ErrorFields.


        :param errors: The errors of this ErrorFields.  # noqa: E501
        :type: list[ErrorField]
        """

        self._errors = errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ErrorFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
