# coding: utf-8

"""
    Easyc External

    API para processo externo  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tecnologia@easycredito.me
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LoanAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'home_since': 'HomeSince'
    }

    attribute_map = {
        'home_since': 'homeSince'
    }

    def __init__(self, home_since=None):  # noqa: E501
        """LoanAddress - a model defined in Swagger"""  # noqa: E501
        self._home_since = None
        self.discriminator = None
        self.home_since = home_since

    @property
    def home_since(self):
        """Gets the home_since of this LoanAddress.  # noqa: E501


        :return: The home_since of this LoanAddress.  # noqa: E501
        :rtype: HomeSince
        """
        return self._home_since

    @home_since.setter
    def home_since(self, home_since):
        """Sets the home_since of this LoanAddress.


        :param home_since: The home_since of this LoanAddress.  # noqa: E501
        :type: HomeSince
        """
        if home_since is None:
            raise ValueError("Invalid value for `home_since`, must not be `None`")  # noqa: E501

        self._home_since = home_since

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoanAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoanAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
