# coding: utf-8

"""
    Easyc External

    API para processo externo  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tecnologia@easycredito.me
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from easycredito.models.credit import Credit


class LoanCredit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'customer_service_number': 'str',
        'type': 'ProductType',
        'product': 'str',
        'has_documents': 'bool',
        'last_status': 'CreditStatus',
        'date_created': 'datetime',
        'last_updated': 'datetime',
        'service_charge': 'float',
        'request_id': 'int',
        'value': 'float',
        'installments': 'int',
        'monthly_tax': 'float',
        'installments_value': 'float',
        'iof_value': 'float',
        'gross_value': 'float',
        'first_payment_date': 'date',
        'cet': 'float',
        'released_date': 'date'
    }
    if hasattr(Credit, "swagger_types"):
        swagger_types.update(Credit.swagger_types)

    attribute_map = {
        'customer_service_number': 'customerServiceNumber',
        'type': 'type',
        'product': 'product',
        'has_documents': 'hasDocuments',
        'last_status': 'lastStatus',
        'date_created': 'dateCreated',
        'last_updated': 'lastUpdated',
        'service_charge': 'serviceCharge',
        'request_id': 'requestId',
        'value': 'value',
        'installments': 'installments',
        'monthly_tax': 'monthlyTax',
        'installments_value': 'installmentsValue',
        'iof_value': 'iofValue',
        'gross_value': 'grossValue',
        'first_payment_date': 'firstPaymentDate',
        'cet': 'cet',
        'released_date': 'releasedDate'
    }
    if hasattr(Credit, "attribute_map"):
        attribute_map.update(Credit.attribute_map)

    def __init__(self, customer_service_number=None, type=None, product=None, has_documents=None, last_status=None, date_created=None, last_updated=None, service_charge=None, request_id=None, value=None, installments=None, monthly_tax=None, installments_value=None, iof_value=None, gross_value=None, first_payment_date=None, cet=None, released_date=None, *args, **kwargs):  # noqa: E501
        """LoanCredit - a model defined in Swagger"""  # noqa: E501
        self._customer_service_number = None
        self._type = None
        self._product = None
        self._has_documents = None
        self._last_status = None
        self._date_created = None
        self._last_updated = None
        self._service_charge = None
        self._request_id = None
        self._value = None
        self._installments = None
        self._monthly_tax = None
        self._installments_value = None
        self._iof_value = None
        self._gross_value = None
        self._first_payment_date = None
        self._cet = None
        self._released_date = None
        self.discriminator = None
        self.customer_service_number = customer_service_number
        self.type = type
        self.product = product
        self.has_documents = has_documents
        self.last_status = last_status
        self.date_created = date_created
        self.last_updated = last_updated
        self.service_charge = service_charge
        self.request_id = request_id
        self.value = value
        self.installments = installments
        self.monthly_tax = monthly_tax
        if installments_value is not None:
            self.installments_value = installments_value
        if iof_value is not None:
            self.iof_value = iof_value
        if gross_value is not None:
            self.gross_value = gross_value
        if first_payment_date is not None:
            self.first_payment_date = first_payment_date
        if cet is not None:
            self.cet = cet
        if released_date is not None:
            self.released_date = released_date
        Credit.__init__(self, *args, **kwargs)

    @property
    def customer_service_number(self):
        """Gets the customer_service_number of this LoanCredit.  # noqa: E501

        Número de serviço da solicitação  # noqa: E501

        :return: The customer_service_number of this LoanCredit.  # noqa: E501
        :rtype: str
        """
        return self._customer_service_number

    @customer_service_number.setter
    def customer_service_number(self, customer_service_number):
        """Sets the customer_service_number of this LoanCredit.

        Número de serviço da solicitação  # noqa: E501

        :param customer_service_number: The customer_service_number of this LoanCredit.  # noqa: E501
        :type: str
        """
        if customer_service_number is None:
            raise ValueError("Invalid value for `customer_service_number`, must not be `None`")  # noqa: E501

        self._customer_service_number = customer_service_number

    @property
    def type(self):
        """Gets the type of this LoanCredit.  # noqa: E501


        :return: The type of this LoanCredit.  # noqa: E501
        :rtype: ProductType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LoanCredit.


        :param type: The type of this LoanCredit.  # noqa: E501
        :type: ProductType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def product(self):
        """Gets the product of this LoanCredit.  # noqa: E501

        Nome do produto  # noqa: E501

        :return: The product of this LoanCredit.  # noqa: E501
        :rtype: str
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this LoanCredit.

        Nome do produto  # noqa: E501

        :param product: The product of this LoanCredit.  # noqa: E501
        :type: str
        """
        if product is None:
            raise ValueError("Invalid value for `product`, must not be `None`")  # noqa: E501

        self._product = product

    @property
    def has_documents(self):
        """Gets the has_documents of this LoanCredit.  # noqa: E501

        Informa se a proposta já possui os documentos  # noqa: E501

        :return: The has_documents of this LoanCredit.  # noqa: E501
        :rtype: bool
        """
        return self._has_documents

    @has_documents.setter
    def has_documents(self, has_documents):
        """Sets the has_documents of this LoanCredit.

        Informa se a proposta já possui os documentos  # noqa: E501

        :param has_documents: The has_documents of this LoanCredit.  # noqa: E501
        :type: bool
        """
        if has_documents is None:
            raise ValueError("Invalid value for `has_documents`, must not be `None`")  # noqa: E501

        self._has_documents = has_documents

    @property
    def last_status(self):
        """Gets the last_status of this LoanCredit.  # noqa: E501


        :return: The last_status of this LoanCredit.  # noqa: E501
        :rtype: CreditStatus
        """
        return self._last_status

    @last_status.setter
    def last_status(self, last_status):
        """Sets the last_status of this LoanCredit.


        :param last_status: The last_status of this LoanCredit.  # noqa: E501
        :type: CreditStatus
        """
        if last_status is None:
            raise ValueError("Invalid value for `last_status`, must not be `None`")  # noqa: E501

        self._last_status = last_status

    @property
    def date_created(self):
        """Gets the date_created of this LoanCredit.  # noqa: E501

        Data da criação da proposta  # noqa: E501

        :return: The date_created of this LoanCredit.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this LoanCredit.

        Data da criação da proposta  # noqa: E501

        :param date_created: The date_created of this LoanCredit.  # noqa: E501
        :type: datetime
        """
        if date_created is None:
            raise ValueError("Invalid value for `date_created`, must not be `None`")  # noqa: E501

        self._date_created = date_created

    @property
    def last_updated(self):
        """Gets the last_updated of this LoanCredit.  # noqa: E501

        Data da última atualização da proposta  # noqa: E501

        :return: The last_updated of this LoanCredit.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this LoanCredit.

        Data da última atualização da proposta  # noqa: E501

        :param last_updated: The last_updated of this LoanCredit.  # noqa: E501
        :type: datetime
        """
        if last_updated is None:
            raise ValueError("Invalid value for `last_updated`, must not be `None`")  # noqa: E501

        self._last_updated = last_updated

    @property
    def service_charge(self):
        """Gets the service_charge of this LoanCredit.  # noqa: E501

        Taxa de serviço  # noqa: E501

        :return: The service_charge of this LoanCredit.  # noqa: E501
        :rtype: float
        """
        return self._service_charge

    @service_charge.setter
    def service_charge(self, service_charge):
        """Sets the service_charge of this LoanCredit.

        Taxa de serviço  # noqa: E501

        :param service_charge: The service_charge of this LoanCredit.  # noqa: E501
        :type: float
        """
        if service_charge is None:
            raise ValueError("Invalid value for `service_charge`, must not be `None`")  # noqa: E501

        self._service_charge = service_charge

    @property
    def request_id(self):
        """Gets the request_id of this LoanCredit.  # noqa: E501

        ID da solicitação de criação das credits. Usado para identificar as credits do mesmo cliente.  # noqa: E501

        :return: The request_id of this LoanCredit.  # noqa: E501
        :rtype: int
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this LoanCredit.

        ID da solicitação de criação das credits. Usado para identificar as credits do mesmo cliente.  # noqa: E501

        :param request_id: The request_id of this LoanCredit.  # noqa: E501
        :type: int
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def value(self):
        """Gets the value of this LoanCredit.  # noqa: E501

        Valor do empréstimo  # noqa: E501

        :return: The value of this LoanCredit.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this LoanCredit.

        Valor do empréstimo  # noqa: E501

        :param value: The value of this LoanCredit.  # noqa: E501
        :type: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def installments(self):
        """Gets the installments of this LoanCredit.  # noqa: E501

        Número de parcelas  # noqa: E501

        :return: The installments of this LoanCredit.  # noqa: E501
        :rtype: int
        """
        return self._installments

    @installments.setter
    def installments(self, installments):
        """Sets the installments of this LoanCredit.

        Número de parcelas  # noqa: E501

        :param installments: The installments of this LoanCredit.  # noqa: E501
        :type: int
        """
        if installments is None:
            raise ValueError("Invalid value for `installments`, must not be `None`")  # noqa: E501

        self._installments = installments

    @property
    def monthly_tax(self):
        """Gets the monthly_tax of this LoanCredit.  # noqa: E501

        Taxa de juros mensal  # noqa: E501

        :return: The monthly_tax of this LoanCredit.  # noqa: E501
        :rtype: float
        """
        return self._monthly_tax

    @monthly_tax.setter
    def monthly_tax(self, monthly_tax):
        """Sets the monthly_tax of this LoanCredit.

        Taxa de juros mensal  # noqa: E501

        :param monthly_tax: The monthly_tax of this LoanCredit.  # noqa: E501
        :type: float
        """
        if monthly_tax is None:
            raise ValueError("Invalid value for `monthly_tax`, must not be `None`")  # noqa: E501

        self._monthly_tax = monthly_tax

    @property
    def installments_value(self):
        """Gets the installments_value of this LoanCredit.  # noqa: E501

        Valor da parcela  # noqa: E501

        :return: The installments_value of this LoanCredit.  # noqa: E501
        :rtype: float
        """
        return self._installments_value

    @installments_value.setter
    def installments_value(self, installments_value):
        """Sets the installments_value of this LoanCredit.

        Valor da parcela  # noqa: E501

        :param installments_value: The installments_value of this LoanCredit.  # noqa: E501
        :type: float
        """

        self._installments_value = installments_value

    @property
    def iof_value(self):
        """Gets the iof_value of this LoanCredit.  # noqa: E501

        Valor do IOF  # noqa: E501

        :return: The iof_value of this LoanCredit.  # noqa: E501
        :rtype: float
        """
        return self._iof_value

    @iof_value.setter
    def iof_value(self, iof_value):
        """Sets the iof_value of this LoanCredit.

        Valor do IOF  # noqa: E501

        :param iof_value: The iof_value of this LoanCredit.  # noqa: E501
        :type: float
        """

        self._iof_value = iof_value

    @property
    def gross_value(self):
        """Gets the gross_value of this LoanCredit.  # noqa: E501

        Valor financiado  # noqa: E501

        :return: The gross_value of this LoanCredit.  # noqa: E501
        :rtype: float
        """
        return self._gross_value

    @gross_value.setter
    def gross_value(self, gross_value):
        """Sets the gross_value of this LoanCredit.

        Valor financiado  # noqa: E501

        :param gross_value: The gross_value of this LoanCredit.  # noqa: E501
        :type: float
        """

        self._gross_value = gross_value

    @property
    def first_payment_date(self):
        """Gets the first_payment_date of this LoanCredit.  # noqa: E501

        Data da primeira parcela  # noqa: E501

        :return: The first_payment_date of this LoanCredit.  # noqa: E501
        :rtype: date
        """
        return self._first_payment_date

    @first_payment_date.setter
    def first_payment_date(self, first_payment_date):
        """Sets the first_payment_date of this LoanCredit.

        Data da primeira parcela  # noqa: E501

        :param first_payment_date: The first_payment_date of this LoanCredit.  # noqa: E501
        :type: date
        """

        self._first_payment_date = first_payment_date

    @property
    def cet(self):
        """Gets the cet of this LoanCredit.  # noqa: E501

        Custo efetivo total anual  # noqa: E501

        :return: The cet of this LoanCredit.  # noqa: E501
        :rtype: float
        """
        return self._cet

    @cet.setter
    def cet(self, cet):
        """Sets the cet of this LoanCredit.

        Custo efetivo total anual  # noqa: E501

        :param cet: The cet of this LoanCredit.  # noqa: E501
        :type: float
        """

        self._cet = cet

    @property
    def released_date(self):
        """Gets the released_date of this LoanCredit.  # noqa: E501

        Data da Liberação do empréstimo  # noqa: E501

        :return: The released_date of this LoanCredit.  # noqa: E501
        :rtype: date
        """
        return self._released_date

    @released_date.setter
    def released_date(self, released_date):
        """Sets the released_date of this LoanCredit.

        Data da Liberação do empréstimo  # noqa: E501

        :param released_date: The released_date of this LoanCredit.  # noqa: E501
        :type: date
        """

        self._released_date = released_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoanCredit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoanCredit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
