# coding: utf-8

"""
    Easyc External

    API para processo externo  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tecnologia@easycredito.me
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ProposalRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'loan_request': 'LoanRequest',
        'card_request': 'CardRequest',
        'products': 'list[ProductType]'
    }

    attribute_map = {
        'loan_request': 'loanRequest',
        'card_request': 'cardRequest',
        'products': 'products'
    }

    def __init__(self, loan_request=None, card_request=None, products=None):  # noqa: E501
        """ProposalRequest - a model defined in Swagger"""  # noqa: E501
        self._loan_request = None
        self._card_request = None
        self._products = None
        self.discriminator = None
        if loan_request is not None:
            self.loan_request = loan_request
        if card_request is not None:
            self.card_request = card_request
        if products is not None:
            self.products = products

    @property
    def loan_request(self):
        """Gets the loan_request of this ProposalRequest.  # noqa: E501


        :return: The loan_request of this ProposalRequest.  # noqa: E501
        :rtype: LoanRequest
        """
        return self._loan_request

    @loan_request.setter
    def loan_request(self, loan_request):
        """Sets the loan_request of this ProposalRequest.


        :param loan_request: The loan_request of this ProposalRequest.  # noqa: E501
        :type: LoanRequest
        """

        self._loan_request = loan_request

    @property
    def card_request(self):
        """Gets the card_request of this ProposalRequest.  # noqa: E501


        :return: The card_request of this ProposalRequest.  # noqa: E501
        :rtype: CardRequest
        """
        return self._card_request

    @card_request.setter
    def card_request(self, card_request):
        """Sets the card_request of this ProposalRequest.


        :param card_request: The card_request of this ProposalRequest.  # noqa: E501
        :type: CardRequest
        """

        self._card_request = card_request

    @property
    def products(self):
        """Gets the products of this ProposalRequest.  # noqa: E501


        :return: The products of this ProposalRequest.  # noqa: E501
        :rtype: list[ProductType]
        """
        return self._products

    @products.setter
    def products(self, products):
        """Sets the products of this ProposalRequest.


        :param products: The products of this ProposalRequest.  # noqa: E501
        :type: list[ProductType]
        """

        self._products = products

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProposalRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProposalRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
